# Generated by Django 2.1.1 on 2018-09-15 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='account',
            fields=[
                ('accountId', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'accounts',
            },
        ),
        migrations.CreateModel(
            name='coin',
            fields=[
                ('coinId', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('symbol', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'coins',
            },
        ),
        migrations.CreateModel(
            name='tradeHistory',
            fields=[
                ('tradeId', models.AutoField(primary_key=True, serialize=False)),
                ('tradeType', models.CharField(max_length=10)),
                ('amount', models.FloatField()),
                ('price', models.FloatField()),
                ('date', models.DateTimeField()),
            ],
            options={
                'db_table': 'trade_history',
            },
        ),
        migrations.CreateModel(
            name='balance',
            fields=[
                ('accountId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='trading_simulator.account')),
                ('USDbalance', models.FloatField()),
                ('BTCbalance', models.FloatField()),
                ('ETHbalance', models.FloatField()),
                ('EOSbalance', models.FloatField()),
            ],
            options={
                'db_table': 'balances',
            },
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='accountId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trading_simulator.account'),
        ),
        migrations.AddField(
            model_name='tradehistory',
            name='coinId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='trading_simulator.coin'),
        ),
    ]
