# Generated by Django 2.1.1 on 2018-09-21 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trading_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='accountId',
            field=models.ForeignKey(db_column='accountId', on_delete=django.db.models.deletion.CASCADE, to='trading_simulator.account'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='coinId',
            field=models.ForeignKey(db_column='coinId', on_delete=django.db.models.deletion.CASCADE, to='trading_simulator.coin'),
        ),
    ]
