# Generated by Django 2.1.1 on 2018-10-11 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_simulator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
