# Generated by Django 2.1.1 on 2018-09-15 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_simulator', '0002_auto_20180915_0904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='BTCbalance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='EOSbalance',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='balance',
            name='ETHbalance',
            field=models.FloatField(blank=True),
        ),
    ]
