# Generated by Django 2.1.1 on 2018-10-09 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_simulator', '0002_account_isadmin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='isAdmin',
            field=models.BooleanField(default=False),
        ),
    ]
