# Generated by Django 2.1.1 on 2018-09-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trading_simulator', '0004_auto_20180915_0937'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='initialAmount',
            field=models.FloatField(default=0),
        ),
    ]
